name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
    # Server address of Docker registry. If not set then will default to Docker Hub
#         registry: # optional
        # Username used to log against the Docker registry
        username: ${{ secrets.uname }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.password }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
          context: .
          push: true
          tags: latest
#           labels: ${{ steps.meta.outputs.labels }}
